// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwyddkmyusoxdjfvmdgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53eWRka215dXNveGRqZnZtZGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjQ1ODIsImV4cCI6MjA3NDAwMDU4Mn0.p-ARBoSZwo8lyV2YkAU28DXYWfu4QKZQGIWa6PAt8J0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});